apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: flight-reservation-service-group
  KAFKA_TOPIC_1: flightreservation-user-topic
  KAFKA_TOPIC_2: user-flightreservation-topic
  KAFKA_TOPIC_3: flightreservation-flight-topic
  KAFKA_TOPIC_4: flight-flightreservation-topic
  #KAFKA_TOPIC_7: flightreservation-receipt-topic
  #KAFKA_TOPIC_8: flightreservation-receipt-topic
  MONGODB_HOSTNAME: flight-reservation-service-db
  MONGODB_PORT: "27017"
kind: ConfigMap
metadata:
  name: flight-reservation-service-env-file
---
apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: user-service-group
  KAFKA_TOPIC_1: flightreservation-user-topic
  KAFKA_TOPIC_2: user-flightreservation-topic
  KAFKA_TOPIC_5: flight-user-topic
  KAFKA_TOPIC_6: flight-user-topic
  MONGODB_HOSTNAME: user-service-db
  MONGODB_PORT: "27017"
kind: ConfigMap
metadata:
  name: user-service-env-file
---
apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: flight-service-group
  KAFKA_TOPIC_3: flightreservation-flight-topic
  KAFKA_TOPIC_4: flight-flightreservation-topic
  KAFKA_TOPIC_5: flight-user-topic
  KAFKA_TOPIC_6: flight-user-topic
  MONGODB_HOSTNAME: flight-service-db
  MONGODB_PORT: "27017"
kind: ConfigMap
metadata:
  name: flight-service-env-file